In [52]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

In [53]:
w_raw = "../weatherpy/weather_df.csv"
weather = pd.read_csv(w_raw)
xna_weather.head(20)

,city,date,cloudiness,humidity,lat,lng,maxtemp,windspeed
0,Sarangani,1589176869,57,75,5.40,125.46,85.12,12.68
1,Ilebo,1589176869,22,92,-4.32,20.58,73.65,0.72
2,Nagtipunan,1589176869,76,45,16.22,121.60,92.21,4.59
3,Ushuaia,1589176759,40,75,-54.80,-68.30,41.00,9.17
4,Mataura,1589176869,100,87,-46.19,168.86,50.07,2.59
5,Puerto Ayora,1589176870,1,94,-0.74,-90.35,75.99,5.46
6,Hermanus,1589176870,6,96,-34.42,19.23,55.99,1.99
7,Esperance,1589176842,52,30,-33.87,121.90,71.60,10.29
8,Khatanga,1589176870,87,99,71.97,102.50,31.51,3.96
9,Rikitea,1589176871,42,75,-23.12,-134.97,75.07,9.78
10,Araouane,1589176871,77,14,18.90,-3.53,84.24,10.78
11,Aksarka,1589176871,62,81,66.56,67.80,42.30,7.14
12,Hilo,1589176872,75,65,19.73,-155.09,77.00,3.27
13,Albany,1589176872,100,68,42.60,-73.97,43.00,2.55
14,Egtved,1589176872,6,66,55.62,9.30,41.00,9.17
15,Linxia Chengguanzhen,1589176873,7,32,35.60,103.21,60.53,3.58
16,Bambous Virieux,1589176873,75,50,-20.34,57.76,77.00,11.41
17,Los Llanos de Aridane,1589176873,48,72,28.66,-17.92,66.20,5.82
18,Makakilo City,1589176874,20,69,21.35,-158.09,78.80,3.36
19,Kruisfontein,1589176874,0,66,-34.00,24.73,59.59,5.64

In [54]:
# Configure gmaps
gmaps.configure(api_key = g_key)
# Locations
locations = xna_weather[["lat", "lng"]]
humidity = xna_weather["humidity"]
# Heatmap
fig = gmaps.figure()
# layer
heat = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)
# Add
fig.add_layer(heat)
# Display
fig

Figure(layout=FigureLayout(height='420px'))

In [55]:
no_clouds = xna_weather[xna_weather["cloudiness"] == 0]
above_70_degrees = no_clouds[no_clouds["maxtemp"] > 70]
below_80_degrees = above_70_degrees[above_70_degrees["maxtemp"] < 80]
slow_wind = below_80_degrees[below_80_degrees["windspeed"] < 10]
ideal_vacation = slow_wind[slow_wind["humidity"] < 60]
ind_vacation = ideal_vacation.reset_index()
del ind_vacation["index"]
ind_vacation

     city        date  cloudiness  humidity    lat    lng  maxtemp  windspeed
0   Ţahţā  1589177027           0        28  26.77  31.50    73.40       6.93
1    Faya  1589177243           0        52  18.39  42.45    71.60       9.17
2  Agadez  1589177314           0        12  19.75  10.25    79.95       2.86
3     Chu  1589177533           0        34  43.60  73.76    77.49       2.10

In [56]:
gmaps.configure(api_key = g_key)
# Locations
locations = ind_vacation[["lat", "lng"]]
humidity = ind_vacation["humidity"]
# Heatmap
fig = gmaps.figure()
# layer
heat = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)
# Add
fig.add_layer(heat)

# Display
fig

Figure(layout=FigureLayout(height='420px'))